version: '2'
services:
  parking_api:
    image: tylerdoll/park_it_better_api
  parking_db:
    image: webhippie/mongodb
    volumes:
      - mongo:/var/lib/mongodb
  parking_ui:
    image: tylerdoll/park_it_better_ui

volumes:
  mongo:
